spring:
  application:
    name: spring-ai-GA
  ai:
    deepseek:
      base-url: https://api.deepseek.com/v1
      api-key: sk-944a55346b8c4f1383b6280cf3b1bf33
      chat:
        options:
          model: deepseek-chat # deepseek-chat??????deepseek-reasoner ????
          # ??
          #temperature: 0.8
          #????????????????????????10~50??
          #???????????????????token???
          #??????????????????????maxTokens?
          #max-tokens: 20
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: INFO # ?????? DEBUG ??????